app:
    name: NEWDCR-E.COM
    code: DCRE-BACK
    exe: DCRE_BACKEND.JAR
    host: BACKENDSERVER
    interfaces:
        user: SYSINTUSER
env:        
    so: windows1
    source: hda
server:
    port: 3001      

spring:
    #datasource:
    #    password: password
    #    url: jdbc:h2:dev
    #    username: SA    
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER    
    devtools:
        add-properties: false  
    datasource:
        #url: jdbc:as400://hsa0014;naming=system;translate binary=true;libraries=,HD4DCDHH,LPDPGICE;user=SB037635;password=SB037635;driverClassName=com.ibm.as400.access.AS400JDBCDriver;hibernate.ddl-auto=validate
        url: jdbc:as400://10.146.0.5;naming=system;translate binary=true;libraries=,HD4DCDHH,LPDPGICE;user=ADTDTI1B;password=loecfxjd;driverClassName=com.ibm.as400.access.AS400JDBCDriver;hibernate.ddl-auto=validate

data:
    proxy:
        host: gateway.zscloud.net
        port: 443
    token_pass: SUPER_SECRET_WORD
    token_expire: 280000000
    api_se:
        api_gateway: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2OTc4OTQ4ODksImV4cCI6MTc2NzIyNTU0MCwiaWRsb2dpbiI6IlNCSU5UMDAxIiwicmF0ZWxpbWl0IjoxMjAsInF1b3RhbGltaXQiOjEwMDAwMH0.DIJUeK6NyEmgZV9i6JBDKcIVoFw6kUBk3gSoILYxZGA
        base_url: https://motohonda-test.softexpert.com/apigateway
        adm: https://motohonda-test.softexpert.com/apigateway/se/ws/adm_ws.php
        form:
        workflow:    
      

as400:
    datasource:
        jdbcUrl:            jdbc:as400://HSA0014;naming=system;libraries=,PTDHD,LPDDBICE:sslConnection=true;
        driver-class-name:  com.ibm.as400.access.AS400JDBCDriver
        username:           SB037635
        password:           SB037635
        database-platform:  org.hibernate.dialect.DB2400Dialect
        hibernate.ddl-auto: validate

schedule:
    reprocPendencyCAD_PRD: 0
    reprocPendencyCAD_AST: 0
    #Reproc docs de 2 em 2 horas 120 ->
    reprocPendencyALL_PRD: 0
    reprocPendencyALL_AST: 0
    atualizaPRD: 0
    reprocMatrizPRD: 10
    reprocMatrizAST: 10
    procTXTShowa: 120

    #old config:
    #atualizaPRD: 15
    #procTXTShowa: 15

    #reprocPendenciaPRD: true
    #reprocPendenciaAST: false
    #atualizaPRD: true
    ##reprocMatrizPRD: false
    #reprocMatrizAST: false
    #procTXTShowa: true


interface:
    txt_showa:                
        dirIN: //hdamdt6196/C$/_DEV/GITL/dcr-backend/in_out/in
        dirOUT: //hdamdt6196/C$/_DEV/GITL/dcr-backend/in_out/out
        dirTMP: //hdamdt6196/C$/_DEV/GITL/dcr-backend/in_out/tmp
        dirPROC: //hdamdt6196/C$/_DEV/GITL/dcr-backend/in_out/processado
storage:
    fileserver: //sahdamvqweb001/c$/fileserver/new-dcr
    approot: C:/sistemas/dcr-backend